import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  accessToken: localStorage.getItem("accessToken"),
  refreshToken: localStorage.getItem("refreshToken"),
  user: null
};

const authSlice = createSlice({
  name: "auth",
  initialState,
  reducers: {
    setTokens(state, action) {
      const accessToken = action.payload.accessToken || action.payload.access_token;
      const refreshToken = action.payload.refreshToken || action.payload.refresh_token;
      state.accessToken = accessToken;
      state.refreshToken = refreshToken;
      if (accessToken) localStorage.setItem("accessToken", accessToken);
      if (refreshToken) localStorage.setItem("refreshToken", refreshToken);
    },
    clearAuth(state) {
      state.accessToken = null;
      state.refreshToken = null;
      state.user = null;
      localStorage.removeItem("accessToken");
      localStorage.removeItem("refreshToken");
    },
    setUser(state, action) {
      state.user = action.payload;
    }
  }
});

export const { setTokens, clearAuth, setUser } = authSlice.actions;
export default authSlice.reducer;
